/**
 * 预设库 —— 每个预设还原一张桌面参考图。
 * 参考图目录：~/Desktop/参数化几何图形参考图/
 * 识别与分类见：docs/parametric-engine/01-reference-analysis.md
 *
 * 尺寸一律用像素（见 preset() 里钉死的 shape.scaleToUnit = false）。
 * 数值经过视觉验收迭代：密度偏低的组合已按"元素更大 / 网格更密"上调过。
 */

import { defaults } from './schema.js';

const INK = '#101216';
const PAPER = '#f2eee6';
const ORANGE = '#FFA500';

/**
 * 预设构造器。
 * 强制 shape.scaleToUnit = false —— 本文件里所有预设的尺寸都按像素书写，
 * 而 DEFAULTS 可能变化，因此在这里显式钉死，避免预设被默认值悄悄改语义。
 * （这正是 p-polar-spiral 曾经渲染成空白的原因：半径被缩成 0.03px）
 */
const preset = (over) => ({ ...defaults(), 'shape.scaleToUnit': false, ...over });

export const PRESETS = [
  {
    id: 'p-iso-maze',
    name: 'Iso Maze',
    nameZh: '等轴测迷宫',
    family: 'grid',
    ref: 'ref-01',
    params: preset({
      'canvas.aspect': 'banner',
      palette: [PAPER, INK, ''],
      'lattice.type': 'iso',
      'lattice.cols': 9,
      'lattice.rows': 22,
      'shape.stroke': true,
      'shape.strokeWidth': 22,
      'topology.mode': 'maze',
      'modulator.seed': 7123,
    }),
  },
  {
    id: 'p-circle-pulse',
    name: 'Circle Pulse',
    nameZh: '圆脉',
    family: 'grid',
    ref: 'ref-02',
    params: preset({
      'canvas.aspect': 'banner',
      palette: [INK, '#ffffff', ''],
      'lattice.type': 'grid',
      'lattice.cols': 8,
      'lattice.rows': 16,
      'lattice.gap': 0,
      'modulator.type': 'sine',
      'modulator.axis': 'y',
      'modulator.freq': 1,
      'modulator.phase': 0.25,
      'modulator.amp': 1,
      'modulator.bias': 0.5,
      'shape.type': 'dot',
      'shape.sizeMin': 38,
      'shape.sizeMax': 66,
    }),
  },
  {
    id: 'p-capsule-noise',
    name: 'Capsule Field',
    nameZh: '胶囊噪声场',
    family: 'grid',
    ref: 'ref-03',
    params: preset({
      palette: [INK, '#ffffff', ''],
      'lattice.type': 'grid',
      'lattice.cols': 8,
      'lattice.rows': 8,
      'modulator.type': 'noise',
      'modulator.axis': 'both',
      'modulator.freq': 1.6,
      'modulator.amp': 0.62,
      'modulator.bias': 0.5,
      'modulator.seed': 7,
      'shape.type': 'capsule',
      'shape.sizeMin': 34,
      'shape.sizeMax': 108,
      'shape.aspect': 1.9,
      'shape.aspectMode': 'modulated',
      'shape.corner': 1,
      'shape.rotMode': 'grid',
    }),
  },
  {
    id: 'p-curved-hex',
    name: 'Curved Hex',
    nameZh: '曲边六角',
    family: 'hex',
    ref: 'ref-04',
    params: preset({
      palette: [INK, '#ffffff', ''],
      'lattice.type': 'hex',
      'lattice.cols': 9,
      'lattice.rows': 11,
      'shape.type': 'curvePoly',
      'shape.sides': 6,
      'shape.curvature': 0.42,
      'shape.sizeMin': 128,
      'shape.sizeMax': 128,
    }),
  },
  {
    id: 'p-phyllotaxis',
    name: 'Phyllotaxis',
    nameZh: '叶序螺旋',
    family: 'spiral',
    ref: 'ref-05',
    params: preset({
      palette: [PAPER, INK, ''],
      'lattice.type': 'phyllotaxis',
      'lattice.count': 1100,
      'lattice.divergence': 137.5,
      'modulator.type': 'linear',
      'modulator.axis': 'radius',
      'modulator.amp': 0.5,
      'modulator.bias': 0.5,
      'shape.type': 'dot',
      'shape.sizeMin': 1.5,
      'shape.sizeMax': 17,
    }),
  },
  {
    id: 'p-diagonal-weave',
    name: 'Diagonal Weave',
    nameZh: '对角编织',
    family: 'grid',
    ref: 'ref-06',
    params: preset({
      'canvas.aspect': 'banner',
      palette: [PAPER, INK, ''],
      'lattice.type': 'grid',
      'lattice.cols': 12,
      'lattice.rows': 26,
      'lattice.gap': 0.12,
      'shape.type': 'bar',
      'shape.sizeMin': 46,
      'shape.sizeMax': 46,
      'shape.rotation': 45,
      'shape.rotMode': 'alternate',
      'shape.stroke': true,
      'shape.strokeWidth': 12,
    }),
  },
  {
    id: 'p-sine-warp',
    name: 'Sine Warp',
    nameZh: '正弦扭曲',
    family: 'grid',
    ref: 'ref-07',
    params: preset({
      'canvas.aspect': 'photo',
      palette: [INK, '#ffffff', ''],
      'lattice.type': 'grid',
      'lattice.cols': 13,
      'lattice.rows': 17,
      'topology.warp': 0.55,
      'topology.warpFreq': 2.4,
      'shape.type': 'dot',
      'shape.sizeMin': 20,
      'shape.sizeMax': 42,
    }),
  },
  {
    id: 'p-polar-spiral',
    name: 'Polar Spiral',
    nameZh: '极坐标螺旋',
    family: 'spiral',
    ref: 'ref-08',
    params: preset({
      'canvas.aspect': 'portrait',
      palette: [INK, ORANGE, ''],
      'lattice.type': 'spiral',
      'lattice.count': 520,
      'lattice.turns': 7.5,
      'lattice.spiralKind': 'archimedean',
      'modulator.type': 'linear',
      'modulator.axis': 'radius',
      'modulator.amp': 0.5,
      'modulator.bias': 0.45,
      'shape.type': 'dot',
      'shape.sizeMin': 3,
      'shape.sizeMax': 34,
    }),
  },
  {
    id: 'p-sine-weave',
    name: 'Sine Weave',
    nameZh: '正弦编织',
    family: 'grid',
    ref: 'ref-09',
    params: preset({
      'canvas.aspect': 'photo',
      palette: [INK, '#ffffff', ''],
      'lattice.type': 'grid',
      'lattice.cols': 11,
      'lattice.rows': 26,
      'modulator.type': 'sine',
      'modulator.axis': 'x',
      'modulator.freq': 1.5,
      'modulator.amp': 1,
      'modulator.bias': 0.5,
      'shape.type': 'dot',
      'shape.sizeMin': 9,
      'shape.sizeMax': 27,
    }),
  },
  {
    id: 'p-decay-grid',
    name: 'Decay Grid',
    nameZh: '消散网格',
    family: 'grid',
    ref: 'ref-10',
    params: preset({
      'canvas.aspect': 'tall',
      palette: [PAPER, INK, ''],
      'lattice.type': 'grid',
      'lattice.cols': 11,
      'lattice.rows': 34,
      'modulator.type': 'linear',
      'modulator.axis': 'y',
      'modulator.amp': -0.5,
      'modulator.bias': 0.9,
      'shape.type': 'polygon',
      'shape.sides': 3,
      'shape.corner': 0.3,
      'shape.sizeMin': 16,
      'shape.sizeMax': 72,
      'topology.jitter': 0.15,
      'topology.warp': 0.22,
      'topology.warpFreq': 1.2,
      'modulator.seed': 3,
    }),
  },
  {
    id: 'p-hex-clusters',
    name: 'Hex Clusters',
    nameZh: '六角点阵簇',
    family: 'hex',
    ref: 'ref-11',
    params: preset({
      palette: [PAPER, INK, ''],
      'lattice.type': 'cluster',
      'lattice.cols': 5,
      'lattice.rows': 9,
      'lattice.clusterSize': 4,
      'lattice.clusterSpread': 2.35,
      'shape.type': 'dot',
      'shape.sizeMin': 22,
      'shape.sizeMax': 22,
    }),
  },
  {
    id: 'p-hex-triangles',
    name: 'Hex Triangles',
    nameZh: '六角三角阵列',
    family: 'hex',
    ref: 'ref-12',
    params: preset({
      'canvas.aspect': 'portrait',
      palette: [PAPER, INK, ''],
      'lattice.type': 'hex',
      'lattice.cols': 8,
      'lattice.rows': 13,
      'modulator.type': 'linear',
      'modulator.axis': 'y',
      'modulator.amp': 0.38,
      'modulator.bias': 0.62,
      'shape.type': 'polygon',
      'shape.sides': 3,
      'shape.corner': 0.34,
      'shape.rotMode': 'radial',
      'shape.sizeMin': 24,
      'shape.sizeMax': 118,
    }),
  },
  {
    id: 'p-spiral-gallery',
    name: 'Spiral Gallery',
    nameZh: '螺旋陈列',
    family: 'spiral',
    ref: 'ref-13',
    params: preset({
      palette: [PAPER, INK, ''],
      'lattice.type': 'phyllotaxis',
      'lattice.count': 700,
      'lattice.divergence': 137.3,
      'shape.type': 'ellipse',
      'shape.aspect': 2.6,
      'shape.rotMode': 'tangent',
      'shape.sizeMin': 2,
      'shape.sizeMax': 26,
    }),
  },
  {
    id: 'p-hex-meander',
    name: 'Hex Meander',
    nameZh: '六角回纹',
    family: 'hex',
    ref: 'ref-14',
    params: preset({
      'canvas.aspect': 'portrait',
      palette: [PAPER, INK, ''],
      'lattice.type': 'hex',
      'lattice.cols': 8,
      'lattice.rows': 14,
      'shape.type': 'arc',
      'shape.sweep': 0.72,
      'shape.sizeMin': 122,
      'shape.sizeMax': 122,
      'shape.stroke': true,
      'shape.strokeWidth': 28,
      'topology.mode': 'truchet',
      'topology.density': 0.95,
      'modulator.seed': 11,
    }),
  },
];

export const PRESET_BY_ID = Object.fromEntries(PRESETS.map((x) => [x.id, x]));
